# Generated by Django 3.2.9 on 2022-01-10 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Categoria.', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da unidade hoteleira.', max_length=50)),
                ('description', models.TextField(help_text='Outros dados sobre a unidade hoteleira')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_active', models.BooleanField()),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='imovel.category')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('county_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commom.county')),
            ],
            options={
                'verbose_name': 'Imovel',
                'verbose_name_plural': 'Imoveis',
                'ordering': ['name', 'company_id'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_no', models.CharField(help_text='Numero do quarto', max_length=10, unique=True)),
                ('description', models.TextField()),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=False)),
                ('imovel_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['imovel_id', 'room_no'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tipo de quarto.', max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Quarto',
                'verbose_name_plural': 'Tipos de Quartos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='room_img/%Y/%m/%d', verbose_name='Room Picture', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imovel.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='room_type_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='imovel.roomtype'),
        ),
        migrations.CreateModel(
            name='ImovelWorkers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.PositiveSmallIntegerField(choices=[(1, 'manager'), (2, 'worker')], default=1)),
                ('imovel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='imovel.imovel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='imovel',
            name='users',
            field=models.ManyToManyField(related_name='imoveis', through='imovel.ImovelWorkers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='imovel',
            unique_together={('name', 'company_id', 'county_id')},
        ),
    ]
