# Generated by Django 3.2.9 on 2022-01-10 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('commom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da empresa.', max_length=255, unique=True)),
                ('nif', models.CharField(help_text='NIF da empresa.', max_length=15, unique=True)),
                ('email', models.EmailField(help_text='E-mail da empresa.', max_length=254, unique=True)),
                ('phone', models.CharField(help_text='Contacto telefónico.', max_length=9, unique=True)),
                ('company_address', models.CharField(help_text='Morada da empresa.', max_length=255)),
                ('details', models.TextField(help_text='Outros dados da empresa.')),
                ('is_active', models.BooleanField(default=True)),
                ('county_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commom.county')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'ordering': ['name', 'county_id', 'nif'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('invoice_amount', models.DecimalField(decimal_places=2, help_text='Valor total a receber.', max_digits=20)),
                ('start_date', models.DateField(help_text='Data de início')),
                ('end_date', models.DateField(help_text='Data de fim')),
                ('invoice_details', models.TextField(help_text='Detalhes da fatura')),
                ('ts_issued', models.DateTimeField(default=django.utils.timezone.now)),
                ('ts_paid', models.DateTimeField(blank=True)),
                ('ts_canceled', models.DateTimeField()),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'Invoicecompany',
                'verbose_name_plural': 'Invoicecompanies',
                'ordering': ['-ts_issued', 'company_id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_profile', models.PositiveSmallIntegerField(choices=[(1, 'owner'), (2, 'manager'), (3, 'worker')], default=1)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CompanyUser',
                'verbose_name_plural': 'CompanyUsers',
                'ordering': ['company', 'user'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(related_name='companies', through='company.CompanyUsers', to=settings.AUTH_USER_MODEL),
        ),
    ]
