# Generated by Django 3.2.9 on 2021-11-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0002_auto_20211125_2054'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date']},
        ),
    ]
