# Generated by Django 3.2.9 on 2022-01-10 13:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imovel', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('checkin_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Checkin Date')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_adults', models.PositiveIntegerField(default=1, help_text='Number of Adult Members')),
                ('no_of_childrens', models.PositiveIntegerField(default=0, help_text='Number of Children')),
                ('reservation_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Reservation Date Time')),
                ('expected_arrival_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Expected Arrival Date Time')),
                ('expected_departure_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Expected Departure Date Time')),
                ('discount_percent', models.DecimalField(decimal_places=2, help_text='Percetagem de desconto', max_digits=5)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Valor total', max_digits=10)),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data de actualizacao')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Active'), (2, 'Canceled'), (3, 'Pending')], default=1)),
                ('reservation_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('customer', models.ForeignKey(help_text='Customer Name', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room_id', models.ForeignKey(help_text='Room id', on_delete=django.db.models.deletion.CASCADE, to='imovel.room')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkout_code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('checkout_date_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Checkout Date')),
                ('checkin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.checkin')),
            ],
        ),
        migrations.AddField(
            model_name='checkin',
            name='reservation_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.reservation'),
        ),
    ]
